### ISSUE TITLE
readmeへの説明の追加

### ISSUE THREAD

**Issue by yaakiyu** [RextTeam/rextlib.py#4]
readmeの説明適当すぎませんかねぇ。
...
追加してほしいのは、「他のリポジトリで利用可能かどうか」です
まぁ単純にsakuraBotで一部使用したいな、って思って
これ使えんのかどうかわからな買ったので。

**Comment by tasuren** [comment]
what
利用可能ってどういうこと

**Comment by yaakiyu** [comment]
sakurabotでrextlibを使っていいかということ。

**Comment by tasuren** [comment]
ライセンスがある以上それに従ってれば何だってOK。

**Comment by yaakiyu** [comment]
なるほど
...BSD4って広告とかに「This product includes software developed by RextTeam.」って文章を書く必要があるらしいけど
RTの宣伝に書いてないよね()

**Comment by yaakiyu** [comment]
というかLICENSEの表記「RextTeam」じゃなくて「the organization」になってるし

**Comment by tasuren** [comment]
> なるほど
> 
> ...BSD4って広告とかに「This product includes software developed by RextTeam.」って文章を書く必要があるらしいけど
> 
> RTの宣伝に書いてないよね()

著作者本人による宣伝だからそれはなんだっていい。

**Comment by tasuren** [comment]
> というかLICENSEの表記「RextTeam」じゃなくて「the organization」になってるし

![image](https://user-images.githubusercontent.com/45121209/197912126-090639bd-bbc7-477b-a64c-27982ce37c1a.jpeg)  
theでRextとかリポジトリのオーナーにかかっているはず。

**Comment by yaakiyu** [comment]
理解
表示しなきゃいけないのは辛いな...
Sakuraに取り入れるのやめるか
